### ISSUE TITLE
Option to use real own infrastructure

### ISSUE THREAD

**Issue by deedos** [alfg/openencoder#41]
Hi. Is it possible to use "machine" on my own infrastructure, like a phisical server/host ? Could I use NFS for my "dest" and "src" ?
thanks in advance

**Comment by alfg** [comment]
Hi @deedos, 

Only S3 is supported at the moment for AWS and DigitalOcean. However, I have plans to add custom S3 providers (such as https://github.com/minio/minio) and FTP as an option.

**Comment by alfg** [comment]
Added support for custom S3 providers and FTP:
https://github.com/alfg/openencoder/pull/43
https://github.com/alfg/openencoder/pull/44
