### ISSUE TITLE
Server Container Always Stops Using Docker

### ISSUE THREAD

**Issue by Futrime** [alfg/openencoder#47]
When using docker, whenever I click on the page buttons, the container will throw a fatal error and collapse, making me have to always restart it. The logs shows that there are always some problems of database, such as:
```
{"level":"fatal","msg":"sql: no rows in result set","time":"2020-10-22T12:04:56Z"
```

By the way, what is the default password set in `/scripts/40_users.sql` ?

**Comment by alfg** [comment]
Hi @Futrime, 

The default user and password should be `admin:password`. 

Sorry, I've been meaning to improve the setup scripts. I'll leave this open as a TODO.

**Comment by alfg** [comment]
Try using the latest from `master`. I've added a few fixes around fatal error handling and the startup sql scripts. You may need to start from a new database volume.

**Comment by Futrime** [comment]
Unfortunately, the problem still exists. Probably it's due to an empty list of worker.
![Screenshot](https://user-images.githubusercontent.com/35801754/97011287-0db31b80-1579-11eb-94c4-1351a4c5eb3d.png)

**Comment by alfg** [comment]
Hmm, yeah that's the issue I thought I fixed when some status fields were empty. How are you running the server? From the Docker image or building from source?

**Comment by Futrime** [comment]
Just run `docker-compose up` using the configurations in docker-compose.yml and the containers are built according to Dockerfile from the latest master clone.

**Comment by Futrime** [comment]
Well. Now I know what happened. At the last collapse, command `docker-compose down` didn't remove the built images, which has been reused, ignoring the update 2 days ago.
After rebuild, bugs have gone with wind.

**Comment by alfg** [comment]
Ah, ok. Glad you got the update. Can this be closed?
